"""empty message

Revision ID: 379190fde938
Revises: aed1c4c28e04
Create Date: 2019-04-02 00:46:31.906867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379190fde938'
down_revision = 'aed1c4c28e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_table', sa.Column('author', sa.String(length=30), nullable=False))
    op.create_foreign_key(None, 'post_table', 'user_table', ['author'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_table', type_='foreignkey')
    op.drop_column('post_table', 'author')
    # ### end Alembic commands ###
