"""empty message

Revision ID: 3fce96c20bf8
Revises: f64df7e9ef92
Create Date: 2019-04-04 14:31:20.324198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fce96c20bf8'
down_revision = 'f64df7e9ef92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_table', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_table', 'desc')
    # ### end Alembic commands ###
