"""empty message

Revision ID: 6fef2a2e8f87
Revises: 379190fde938
Create Date: 2019-04-02 00:51:22.946151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fef2a2e8f87'
down_revision = '379190fde938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_table', sa.Column('author', sa.String(length=30), nullable=False))
    op.create_foreign_key(None, 'post_table', 'user_table', ['author'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_table', type_='foreignkey')
    op.drop_column('post_table', 'author')
    # ### end Alembic commands ###
