"""empty message

Revision ID: f64df7e9ef92
Revises: 6fef2a2e8f87
Create Date: 2019-04-04 13:34:16.655775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64df7e9ef92'
down_revision = '6fef2a2e8f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_table', sa.Column('thumb', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'post_table', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_table', type_='unique')
    op.drop_column('post_table', 'thumb')
    # ### end Alembic commands ###
