"""empty message

Revision ID: fe9bfcfce439
Revises: 2c0b61bd2967
Create Date: 2019-03-16 14:09:08.657824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9bfcfce439'
down_revision = '2c0b61bd2967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_table', sa.Column('author_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'post_table', 'user_table', ['author_name'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_table', type_='foreignkey')
    op.drop_column('post_table', 'author_name')
    # ### end Alembic commands ###
